---
- name: restart prometheus
  ansible.builtin.systemd:
    name: "{{ prometheus_unit | default('prometheus.service') }}"
    state: restarted
    daemon_reload: true

- name: restart alertmanager
  ansible.builtin.systemd:
    name: "{{ alertmanager_unit }}"
    state: restarted
    daemon_reload: true


- name: restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted

    