---
- name: Reload prometheus
  become: true
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded
  register: _prom_reload
  failed_when: false

- name: restart_prometheus
  become: true
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: true


- name: restart alertmanager
  ansible.builtin.systemd:
    name: "{{ alertmanager_unit }}"
    state: restarted
    daemon_reload: true


- name: restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted

    