---
- name: Ensure remote tmp exists (for become_user=postgres modules)
  ansible.builtin.file:
    path: /tmp/.ansible-postgres/tmp
    state: directory
    owner: postgres
    group: postgres
    mode: "0700"
  become: true

- name: Install DB packages
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-client
      - prometheus-postgres-exporter
      - python3-psycopg2
      - ufw
    state: present
    update_cache: true
  become: true

