- name: Restart prometheus-postgres-exporter
  ansible.builtin.systemd:
    name: prometheus-postgres-exporter
    state: restarted
  become: true

- name: Restart postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
  become: true

- name: Reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted
  become: true
  
- name: Reload prometheus
  become: true
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded
  register: _prom_reload
  failed_when: false