ansible_user: opx
ansible_ssh_private_key_file: /home/opx/.ssh/opx_key

docker_users:
  - opx

docker_daemon:
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"
  storage-driver: "overlay2"

  docker_daemon:
  insecure-registries:
    - "docker-vm:5000"
    - "192.168.55.30:5000"