---
# Where Prometheus will bind
prometheus_listen_address: "0.0.0.0:9090"
prometheus_retention_time: "15d"
prometheus_scrape_interval: "15s"
prometheus_evaluation_interval: "15s"

# Alertmanager
alertmanager_listen_address: "0.0.0.0:9093"

# Grafana
grafana_listen_address: "0.0.0.0"
grafana_port: 3000
grafana_admin_user: "admin"
grafana_admin_password: "ChangeMeNow_Immediately"

prometheus_node_targets:
  - { ip: "192.168.1.60",  node: "lb-vm" }
  - { ip: "192.168.55.10", node: "mgmt-vm" }
  - { ip: "192.168.55.20", node: "db-vm" }
  - { ip: "192.168.55.30", node: "docker-vm" }
  - { ip: "192.168.55.40", node: "monitor-vm" }
  - { ip: "192.168.55.50", node: "k8smaster-vm" }
  - { ip: "192.168.55.60", node: "k8sworker-vm" }
