---
# Prometheus
prometheus_listen_address: "0.0.0.0:9090"
prometheus_retention_time: "15d"
prometheus_scrape_interval: "15s"
prometheus_evaluation_interval: "15s"

# Alertmanager
alertmanager_listen_address: "0.0.0.0:9093"

# Grafana
grafana_listen_address: "0.0.0.0"
grafana_port: 3000
grafana_admin_user: "admin"
grafana_admin_password: "ChangeMeNow_Immediately"

# Node exporter port on all nodes
node_exporter_port: 9100

# Which inventory groups should be scraped (add/remove groups freely)
prometheus_scrape_groups:
  - lb
  - mgmt
  - db
  - docker
  - monitor
  - k8s_master
  - k8s_worker
