- name: restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted

- name: Reload netfilter rules
  ansible.builtin.shell: iptables-restore < /etc/iptables/rules.v4
  args:
    executable: /bin/bash
  changed_when: true

- name: Save netfilter rules
  ansible.builtin.command: netfilter-persistent save
  changed_when: true