- name: Reload netfilter rules
  ansible.builtin.command: iptables-restore < /etc/iptables/rules.v4
  changed_when: true

- name: Save netfilter rules
  ansible.builtin.command: netfilter-persistent save
  changed_when: true