- name: Configure all other VMs
  hosts: all:!lb
  become: true
  roles:
    - common
    - { role: mgmt,       when: "'mgmt' in group_names" }
    - { role: db,         when: "'db' in group_names" }
    - { role: docker,     when: "'docker' in group_names" }
    - { role: monitor,    when: "'monitor' in group_names" }
    - { role: k8s_master, when: "'k8s_master' in group_names" }
    - { role: k8s_worker, when: "'k8s_worker' in group_names" }
