$ANSIBLE_VAULT;1.1;AES256
35386666633431383962653232643037666533383738616137646266316139626266326162303634
3330376131303061396265376132376636316335313666340a666230626265653361326230643730
37333635316130373437323333646661623039623165343438643738663937356465373137306139
3366633738623637660a666165336135663934646162383764303536316235643462313734396465
30393162633030316135333563383961633936656565363132323631623666653631373535323966
3638366331356238356238633038646566613331383131316432
